version: '3'

# x-superset-image: &superset-image ferrettivinicius/superset
# x-superset-volumes: &superset-volumes
#   - ./superset/docker:/app/docker
#   - ./superset/superset_home:/app/superset_home

networks:
  net:
    driver: bridge

services:
    minio:
          image: minio/minio:latest
          hostname: minio
          container_name: minio
          environment:
            - MINIO_ROOT_USER=aulafia 
            - MINIO_ROOT_PASSWORD=aulafia@123
          volumes:
            - ./minio:/data
          networks:
            - net
          ports:
            - 9000:9000
            - 9001:9001
          command: server /data --console-address ":9001"

    postgres:
      image: postgres:14
      container_name: postgres
      restart: unless-stopped
      volumes:
        - ./postgres/data:/var/lib/postgresql/data
      networks:
        - net
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=aulafia
        - POSTGRES_PASSWORD=aulafia@123
        - POSTGRES_DB=db_aulafia
        - PGDATA=/var/lib/postgresql/data

    mysql:  # Adicionando o serviço MySQL
      image: mysql:latest
      container_name: mysql
      restart: unless-stopped
      volumes:
        - ./mysql/data:/var/lib/mysql
      networks:
        - net
      ports:
        - 3306:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
        # - MYSQL_USER=user  # Adicionei o nome de usuário aqui
        # - MYSQL_PASSWORD=user  # Adicionei a senha do usuário aqui
        - MYSQL_DATABASE=db_aulafia

    airflow:
      image: ferrettivinicius/airflow-aula-fia:latest
      hostname: airflow
      container_name: airflow
      depends_on:
        - postgres
      volumes:
          - ./airflow/dags:/usr/local/airflow/dags
          - ./airflow/jars:/usr/local/airflow/jars
          - ./airflow/config:/usr/local/airflow/config
          - ./airflow/plugins:/usr/local/airflow/plugins
          - ./airflow/tmp_files:/usr/local/ariflow/tmp_files
      networks:
          - net
      ports:
          - 8081:8080

    # nifi:
    #   image: apache/nifi:1.15.3
    #   restart: always
    #   hostname: nifi
    #   container_name: nifi
    #   ports:
    #     - 8080:8080
    #   environment:
    #     - NIFI_WEB_HTTP_PORT=8080
    #   networks:
    #     - net
    #   volumes:
    #     - ./nifi/conf:/opt/nifi/nifi-current/conf

    jupyter:
      image: jupyter/pyspark-notebook:spark-3.2.1
      hostname: jupyter
      container_name: jupyter
      ports:
        - 8888:8888
      networks:
        - net
      volumes:
        - ./jupyter/notebooks:/home/jovyan/notebooks
        - ./jupyter/jars:/home/jovyan/jars